/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author admin
 */
public class purchase_order_main_page extends javax.swing.JFrame {

    /**
     * Creates new form purchase_order_main_page
     */
    public purchase_order_main_page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton6 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        BTviewItemList = new javax.swing.JButton();
        BTviewSupplierList = new javax.swing.JButton();
        BTmanageRequisition = new javax.swing.JButton();
        BTmanagePurchaseOrder = new javax.swing.JButton();
        BTviewPurchaseOrderList = new javax.swing.JButton();

        jButton6.setBackground(new java.awt.Color(255, 204, 255));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 0, 0));
        jButton6.setText("Manage Purchase Order");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setBackground(new java.awt.Color(153, 153, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("WELCOME");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(15, 15, 15))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        BTviewItemList.setBackground(new java.awt.Color(204, 255, 204));
        BTviewItemList.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BTviewItemList.setForeground(new java.awt.Color(0, 0, 0));
        BTviewItemList.setText("View Item List");
        BTviewItemList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTviewItemListActionPerformed(evt);
            }
        });

        BTviewSupplierList.setBackground(new java.awt.Color(255, 255, 204));
        BTviewSupplierList.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BTviewSupplierList.setForeground(new java.awt.Color(0, 0, 0));
        BTviewSupplierList.setText("View Supplier List");
        BTviewSupplierList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTviewSupplierListActionPerformed(evt);
            }
        });

        BTmanageRequisition.setBackground(new java.awt.Color(255, 204, 204));
        BTmanageRequisition.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BTmanageRequisition.setForeground(new java.awt.Color(0, 0, 0));
        BTmanageRequisition.setText("Manage Requisition");
        BTmanageRequisition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTmanageRequisitionActionPerformed(evt);
            }
        });

        BTmanagePurchaseOrder.setBackground(new java.awt.Color(255, 204, 255));
        BTmanagePurchaseOrder.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BTmanagePurchaseOrder.setForeground(new java.awt.Color(0, 0, 0));
        BTmanagePurchaseOrder.setText("Manage Purchase Order");
        BTmanagePurchaseOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTmanagePurchaseOrderActionPerformed(evt);
            }
        });

        BTviewPurchaseOrderList.setBackground(new java.awt.Color(204, 255, 255));
        BTviewPurchaseOrderList.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BTviewPurchaseOrderList.setForeground(new java.awt.Color(0, 0, 0));
        BTviewPurchaseOrderList.setText("View Purchase Order List");
        BTviewPurchaseOrderList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTviewPurchaseOrderListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTviewPurchaseOrderList, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTmanagePurchaseOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTmanageRequisition, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTviewSupplierList, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTviewItemList, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(BTviewItemList, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(BTviewSupplierList, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(BTmanageRequisition, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(BTmanagePurchaseOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(BTviewPurchaseOrderList, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTviewItemListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTviewItemListActionPerformed
        this.dispose();
        item_list ITpage = new item_list();
        ITpage.setVisible(true);
    }//GEN-LAST:event_BTviewItemListActionPerformed

    private void BTviewSupplierListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTviewSupplierListActionPerformed
        this.dispose();
        supplier_list splpage = new supplier_list();
        splpage.setVisible(true);
    }//GEN-LAST:event_BTviewSupplierListActionPerformed

    private void BTmanageRequisitionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTmanageRequisitionActionPerformed
        this.dispose();
        manage_requisition mrpage = new manage_requisition();
        mrpage.setVisible(true);
    }//GEN-LAST:event_BTmanageRequisitionActionPerformed

    private void BTmanagePurchaseOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTmanagePurchaseOrderActionPerformed
        this.dispose();
        manage__purchaseorder mpopage = new manage__purchaseorder();
        mpopage.setVisible(true);
    }//GEN-LAST:event_BTmanagePurchaseOrderActionPerformed

    private void BTviewPurchaseOrderListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTviewPurchaseOrderListActionPerformed
        this.dispose();
        purchase_order_list polpage = new purchase_order_list();
        polpage.setVisible(true);
    }//GEN-LAST:event_BTviewPurchaseOrderListActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(purchase_order_main_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(purchase_order_main_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(purchase_order_main_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(purchase_order_main_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new purchase_order_main_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTmanagePurchaseOrder;
    private javax.swing.JButton BTmanageRequisition;
    private javax.swing.JButton BTviewItemList;
    private javax.swing.JButton BTviewPurchaseOrderList;
    private javax.swing.JButton BTviewSupplierList;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
